version: 2.1
orbs:
  slack: circleci/slack@4.4.4
executors:
  my-executor:
    docker:
      - image: cimg/node:lts
commands:
  test-echo:
    steps:
      - run: echo Hello CircleCI
  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1
  notify_slack_fail:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
jobs:
  build:
    executor:
      name: my-executor
    steps:
      - test-echo
      - notify_slack_pass
      - notify_slack_fail